version: "3.8"
services:
  vitejs-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: hrnet_client-dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
