name: test and push docker image

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "21"
      - name: build image
        run: docker build -t drskyjs/htnet-client_test -f Dockerfile.dev .
      - name: Run tests
        run: docker run drskyjs/htnet-client_test npm run test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login Docker
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build image
        run: docker build -t drskyjs/hrnet-client .
      - name: Push image
        run: docker push drskyjs/hrnet-client
